Feat: Input suggestions
push-platform/push-webchat pull request #43
Opened 2020-09-17 12:50 UTC by paulobernardoaf

**Proposed changes**:
- Added input suggestions support

**Status (please check what you already did)**:
- [X] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog

2020-09-17 17:18 UTC, ricardovasconcelos commented on src/components/Widget/components/Conversation/components/Sender/components/Suggestions/styles.scss
> +    border-top: 1px solid #b5b5b5;
Top! único feedback é sempre usar as cores que estão no scss, nesse caso será o $grey-3

2020-09-17 17:20 UTC, ricardovasconcelos approved these changes

2020-09-22 11:36 UTC, johncordeiro requested changes

2020-09-22 11:36 UTC, johncordeiro commented on src/index.js
> +  suggestionsUrl: 'https://api-staging.bothub.it/v2/repository/examples/search_repositories_examples/',
Can you change the default value for URL for https://api.bothub.it instead of https://api-staging.bothub.it

2020-09-22 11:48 UTC, johncordeiro approved these changes

2020-09-22 11:50 UTC, ricardovasconcelos commented on src/components/Widget/components/Conversation/components/Sender/components/Suggestions/index.js
> +    element.scrollLeft += this.state.scrollDistance + 10;
The functions left and right appear to be the same, on function right() should be element.scrollRight ?
maybe it's better create just one function and get element.scroll by params

2020-09-22 13:06 UTC, ricardovasconcelos commented on src/components/Widget/components/Conversation/components/Sender/components/Suggestions/index.js
> +  scroll = (direction) => {
Great!!

2020-09-24 01:59 UTC, merged